name = "cfedgechat"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
# The following variables are public and can be safely committed to the repository.
DJANGO_WEBHOOK_URL = "https://api.unibooks.app/api/v1/messaging/webhook/edge-chat/"
APP_ORIGINS = "https://unibooks.app,https://unibooksfe.pages.dev"
ALLOWED_IMAGE_HOSTS = "https://assets.unibooks.app"

# Uncomment the following to override variables for Preview or Development environments:
# [env.preview.vars]
# DJANGO_WEBHOOK_URL = "https://dev-api.unibooks.app/api/v1/messaging/webhook/edge-chat/"
# APP_ORIGINS = "http://localhost:4200"
# ENVIRONMENT = "development"

[[durable_objects.bindings]]
name = "CHAT_ROOM"
class_name = "ChatRoom"

[[durable_objects.bindings]]
name = "USER_HUB"
class_name = "UserHub"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["UserHub"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1